In [1]:
# Approach 1 of removing numbers

# Write a function
# Implement the function on your column
# Vectorize your new column
# See how many columns you have

In [2]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk
import pandas as pd
from nltk.stem import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()
from sklearn.feature_extraction.text import CountVectorizer
vectorizer=CountVectorizer()

In [4]:
spam=pd.read_csv("SPAM Data.csv")

In [5]:
new_stopwords=stopwords.words("english")

In [6]:
def datacleaning(x):
    y=nltk.word_tokenize(x)
    temp=[]
    for i in y:
        if i in new_stopwords:
            pass
        else:
            temp.append(i)
    string=' '.join(temp)
    return (string)

In [7]:
spam['Clean_message']=spam['Message'].apply(datacleaning)

In [8]:
spam

,Category,Message,Clean_message
0,ham,"Go until jurong point, crazy.. Available only ...","Go jurong point , crazy .. Available bugis n g..."
1,ham,Ok lar... Joking wif u oni...,Ok lar ... Joking wif u oni ...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry 2 wkly comp win FA Cup final tkts 2...
3,ham,U dun say so early hor... U c already then say...,U dun say early hor ... U c already say ...
4,ham,"Nah I don't think he goes to usf, he lives aro...","Nah I n't think goes usf , lives around though"
...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,This 2nd time tried 2 contact u. U £750 Pound ...
5568,ham,Will ü b going to esplanade fr home?,Will ü b going esplanade fr home ?
5569,ham,"Pity, * was in mood for that. So...any other s...","Pity , * mood . So ... suggestions ?"
5570,ham,The guy did some bitching but I acted like i'd...,The guy bitching I acted like 'd interested bu...
5571,ham,Rofl. Its true to its name,Rofl . Its true name

In [11]:
def my_lemmatizer(a):
    c=nltk.word_tokenize(a)
    list=[]
    for i in c:
        list.append(lemmatizer.lemmatize(i))
        new_string=' '.join(list)
    return new_string

In [12]:
spam['Lemmatized_message']=spam['Clean_message'].apply(my_lemmatizer)

In [13]:
spam

,Category,Message,Clean_message,Lemmatized_message
0,ham,"Go until jurong point, crazy.. Available only ...","Go jurong point , crazy .. Available bugis n g...","Go jurong point , crazy .. Available bugis n g..."
1,ham,Ok lar... Joking wif u oni...,Ok lar ... Joking wif u oni ...,Ok lar ... Joking wif u oni ...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry 2 wkly comp win FA Cup final tkts 2...,Free entry 2 wkly comp win FA Cup final tkts 2...
3,ham,U dun say so early hor... U c already then say...,U dun say early hor ... U c already say ...,U dun say early hor ... U c already say ...
4,ham,"Nah I don't think he goes to usf, he lives aro...","Nah I n't think goes usf , lives around though","Nah I n't think go usf , life around though"
...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,This 2nd time tried 2 contact u. U £750 Pound ...,This 2nd time tried 2 contact u. U £750 Pound ...
5568,ham,Will ü b going to esplanade fr home?,Will ü b going esplanade fr home ?,Will ü b going esplanade fr home ?
5569,ham,"Pity, * was in mood for that. So...any other s...","Pity , * mood . So ... suggestions ?","Pity , * mood . So ... suggestion ?"
5570,ham,The guy did some bitching but I acted like i'd...,The guy bitching I acted like 'd interested bu...,The guy bitching I acted like 'd interested bu...
5571,ham,Rofl. Its true to its name,Rofl . Its true name,Rofl . Its true name

In [14]:
def Text_count(x):
    y=nltk.word_tokenize(x)
    temp=[]
    for i in y: 
         temp.append(i)
    d=' '.join(temp)
    return(len(d.split()))

In [15]:
spam['Text_Length']=spam['Clean_message'].apply(Text_count)

In [16]:
spam

,Category,Message,Clean_message,Lemmatized_message,Text_Length
0,ham,"Go until jurong point, crazy.. Available only ...","Go jurong point , crazy .. Available bugis n g...","Go jurong point , crazy .. Available bugis n g...",20
1,ham,Ok lar... Joking wif u oni...,Ok lar ... Joking wif u oni ...,Ok lar ... Joking wif u oni ...,8
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry 2 wkly comp win FA Cup final tkts 2...,Free entry 2 wkly comp win FA Cup final tkts 2...,32
3,ham,U dun say so early hor... U c already then say...,U dun say early hor ... U c already say ...,U dun say early hor ... U c already say ...,11
4,ham,"Nah I don't think he goes to usf, he lives aro...","Nah I n't think goes usf , lives around though","Nah I n't think go usf , life around though",10
...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,This 2nd time tried 2 contact u. U £750 Pound ...,This 2nd time tried 2 contact u. U £750 Pound ...,27
5568,ham,Will ü b going to esplanade fr home?,Will ü b going esplanade fr home ?,Will ü b going esplanade fr home ?,8
5569,ham,"Pity, * was in mood for that. So...any other s...","Pity , * mood . So ... suggestions ?","Pity , * mood . So ... suggestion ?",9
5570,ham,The guy did some bitching but I acted like i'd...,The guy bitching I acted like 'd interested bu...,The guy bitching I acted like 'd interested bu...,16
5571,ham,Rofl. Its true to its name,Rofl . Its true name,Rofl . Its true name,5

In [18]:
def remove_num(x):
    temp=[]
    for i in x:
        if i.isdigit(): 
            pass
        else:
            temp.append(i)
    my_newsttr=''.join(temp)
    return my_newsttr

In [19]:
remove_num("i have 5 bars right now and 3 at home")

'i have  bars right now and  at home'

In [20]:
spam['No_numbers']=spam['Clean_message'].apply(remove_num)

In [21]:
spam

,Category,Message,Clean_message,Lemmatized_message,Text_Length,No_numbers
0,ham,"Go until jurong point, crazy.. Available only ...","Go jurong point , crazy .. Available bugis n g...","Go jurong point , crazy .. Available bugis n g...",20,"Go jurong point , crazy .. Available bugis n g..."
1,ham,Ok lar... Joking wif u oni...,Ok lar ... Joking wif u oni ...,Ok lar ... Joking wif u oni ...,8,Ok lar ... Joking wif u oni ...
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,Free entry 2 wkly comp win FA Cup final tkts 2...,Free entry 2 wkly comp win FA Cup final tkts 2...,32,Free entry wkly comp win FA Cup final tkts st...
3,ham,U dun say so early hor... U c already then say...,U dun say early hor ... U c already say ...,U dun say early hor ... U c already say ...,11,U dun say early hor ... U c already say ...
4,ham,"Nah I don't think he goes to usf, he lives aro...","Nah I n't think goes usf , lives around though","Nah I n't think go usf , life around though",10,"Nah I n't think goes usf , lives around though"
...,...,...,...,...,...,...
5567,spam,This is the 2nd time we have tried 2 contact u...,This 2nd time tried 2 contact u. U £750 Pound ...,This 2nd time tried 2 contact u. U £750 Pound ...,27,This nd time tried contact u. U £ Pound prize...
5568,ham,Will ü b going to esplanade fr home?,Will ü b going esplanade fr home ?,Will ü b going esplanade fr home ?,8,Will ü b going esplanade fr home ?
5569,ham,"Pity, * was in mood for that. So...any other s...","Pity , * mood . So ... suggestions ?","Pity , * mood . So ... suggestion ?",9,"Pity , * mood . So ... suggestions ?"
5570,ham,The guy did some bitching but I acted like i'd...,The guy bitching I acted like 'd interested bu...,The guy bitching I acted like 'd interested bu...,16,The guy bitching I acted like 'd interested bu...
5571,ham,Rofl. Its true to its name,Rofl . Its true name,Rofl . Its true name,5,Rofl . Its true name

In [22]:
vectorizer.fit(spam['No_numbers'])

CountVectorizer()

In [23]:
vectorizer.get_feature_names_out()[0:100]

array(['____', 'aa', 'aah', 'aaniye', 'aaooooright', 'aathi', 'ab',
       'abbey', 'abdomen', 'abeg', 'abel', 'aberdeen', 'abi', 'ability',
       'abiola', 'abj', 'able', 'abnormally', 'about', 'aboutas',
       'abroad', 'absence', 'absolutely', 'absolutly', 'abstract', 'abt',
       'abta', 'aburo', 'abuse', 'abusers', 'ac', 'academic', 'acc',
       'accent', 'accenture', 'accept', 'access', 'accessible',
       'accidant', 'accident', 'accidentally', 'accommodation',
       'accommodationvouchers', 'accomodate', 'accomodations', 'accordin',
       'accordingly', 'account', 'accounting', 'accounts', 'accumulation',
       'achan', 'ache', 'achieve', 'acid', 'acknowledgement', 'aclpm',
       'acnt', 'aco', 'across', 'act', 'acted', 'actin', 'acting',
       'action', 'activ', 'activate', 'active', 'activities', 'actor',
       'actual', 'actually', 'ad', 'ada', 'adam', 'add', 'addamsfa',
       'added', 'addicted', 'addie', 'adding', 'address', 'adds',
       'adewale', 'adi', 'adjustable', 'admin', 'administrator',
       'admirer', 'admission', 'admit', 'adore', 'adoring', 'adp',
       'adress', 'adrian', 'adrink', 'ads', 'adsense', 'adult'],
      dtype=object)

In [25]:
vector=vectorizer.transform(spam['No_numbers'])

In [26]:
vector

<5572x7797 sparse matrix of type '<class 'numpy.int64'>'
	with 50587 stored elements in Compressed Sparse Row format>

In [27]:
b=vector.toarray()

In [28]:
b

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [29]:
len(vectorizer.get_feature_names_out())

7797